In [202]:
import matplotlib
matplotlib.use('TkAgg')  # or 'Qt5Agg'
import numpy as np
import simpy
import matplotlib.pyplot as plt
import random
import pandas as pd
from pomocnicze_funkcje import readable_time, randomized_service_time, stats, print_statistics

#Naprawa importów pomocniczych funkcji po edycji ich kodu
import importlib
import pomocnicze_funkcje
importlib.reload(pomocnicze_funkcje)

In [203]:
class Patient:
    def __init__(self, id):
        self.id = id
        self.arrival_time = None
        self.service_start_time = None
        self.service_end_time = None
        self.room = None
        self.real_service_time = None

In [204]:
class Room:
    def __init__(self, id, env):
        self.id = id
        self.patients_served = 0
        self.no_show = 0
        self.queue = []
        self.queue_len_dict = dict()
        self.resource = simpy.Resource(env, capacity=1)
    def update_queue_len_dict(self, curr_time):
        self.queue_len_dict[curr_time] = len(self.queue)

In [205]:
class Clinic:
    def __init__(self, number_of_rooms, planned_service_time, no_show_proportion=0.2, seed=None, sim_time=480):
        # zapisanie parametrów 
        self.env = simpy.Environment()
        self.curr_patient_id = 1
        self.planned_service_time = planned_service_time
        self.no_show_proportion = no_show_proportion
        self.sim_time = sim_time
        # utworzenie pokoi
        self.list_rooms = [Room(id=i + 1, env=self.env) for i in range(number_of_rooms)]
        self.processed_patients = []
        

        self.seed = seed
        if self.seed:
            random.seed(self.seed)
            np.random.seed(self.seed)

    def generate_patients(self, room, verbose=False):

        def time_between_new_patients(): # funkcja podajaca czas miedzy wizytami
            return self.planned_service_time

        while True:
            if self.env.now > self.sim_time - self.planned_service_time:  # Pacjenci nie przychodzą przed {planned_service_time} zamknięciem
                break
            
            # tworzymy pacjenta i nadajemu mu atrybuty
            patient = Patient(id=f"{room.id}.{self.curr_patient_id}")
            patient.room = room.id
            patient.real_service_time = randomized_service_time()

            #sprawdzamy no_show
            if random.random() < self.no_show_proportion:  #pacjent nie przyszedl
                if verbose:
                    print(f'Czas {readable_time(self.env.now)}: Pacjent {patient.id} nie pojawił w gabinecie {room.id} w ciągu {self.planned_service_time} minut')
                room.no_show += 1


            else:  #pacjent przyszedl
                patient.arrival_time = self.env.now
                if verbose:
                    print(f"Czas {readable_time(self.env.now)}: Pacjent {patient.id} przybył do kliniki")
                self.env.process(self.serve_patient(patient, room, verbose))

            self.curr_patient_id += 1
            yield self.env.timeout(time_between_new_patients())

    def serve_patient(self, patient, room, verbose=False):
        # pacjent wchodzi do kolejki
        room.queue.append(patient.id)
        room.update_queue_len_dict(curr_time=self.env.now)

        with room.resource.request() as request:
            yield request
            # pacjent wychodzi z kolejki i wchodzi do gabinetu
            patient.service_start_time = self.env.now
            room.queue.remove(patient.id)
            room.update_queue_len_dict(curr_time=self.env.now)
            if verbose:
                print(f"Czas {readable_time(self.env.now)}: Pacjent {patient.id} wchodzi do gabinetu {room.id} ")
            yield self.env.timeout(patient.real_service_time)
            # pacjent wychodzi z gabinetu
            patient.service_end_time = self.env.now
            room.patients_served += 1
            if verbose:
                print(f"Czas {readable_time(self.env.now)}: Pacjent {patient.id} wychodzi z gabinetu {room.id}")
            self.processed_patients.append(patient)

    def reset(self):
        self.env = simpy.Environment()
        self.curr_patient_id = 1
        self.list_rooms = [Room(id=i + 1, env=self.env) for i in range(len(self.list_rooms))]
        self.processed_patients = []

    def run(self, day=1, verbose=False):
        # funkcja do laczenia slownikow z kolejkami w jednen DataFrame
        def sum_queue_len_data():
            all_times = set()
            for room in self.list_rooms:
                all_times.update(room.queue_len_dict.keys())

            all_times = sorted(all_times)
            queue_data = []
            last_known = {room.id: 0 for room in self.list_rooms}

            for time in all_times:
                for room in self.list_rooms:
                    if time in room.queue_len_dict:
                        last_known[room.id] = room.queue_len_dict[time]

                total_queue = sum(last_known.values())
                queue_data.append({
                    'day': day,
                    'time': time,
                    'total_queue_length': total_queue
                })
            queue_data = pd.DataFrame(queue_data)
            queue_data = queue_data.set_index(["day", "time"])
            return queue_data
        
        # Dla kazdego pokoju uruchamiamy osobny proces generowania i obslugi pacjentow
        for room in self.list_rooms:
            self.env.process(self.generate_patients(room, verbose))
        # Symulacja trwa do ustalonego czasu + 0.01 minuity aby rekordy ostatnich pacjentow zdarzyły zostać zapisane
        self.env.run(until=self.sim_time + 0.01)
        # Zapisujemy do pandas DataFrame
        df = pd.DataFrame([
            {
                "day": day,
                "id": p.id,
                "room": p.room,
                "arrival_time": p.arrival_time,
                "service_start_time": p.service_start_time,
                "service_end_time": p.service_end_time,
                "service_time": p.service_end_time - p.service_start_time,
                "waiting_time": p.service_start_time - p.arrival_time
            }
            for p in self.processed_patients
        ])
        # df = df.set_index("id")
        queue_df = sum_queue_len_data()
        return df.set_index(["day", "id"]), queue_df

    def run_multiple_times(self, n, verbose=False, verbose_proportions=False):
        no_show_per_day = []
        sum_no_show = 0
        sum_patients_served = 0

        for i in range(1, n + 1):
            if verbose:
                print(f"-----------{i}-----------")
            self.reset()
            single_df, single_queue_df = self.run(i, verbose)

            no_show_daily = 0

            for room in self.list_rooms:
                no_show_daily += room.no_show
                sum_patients_served += room.patients_served
            no_show_per_day.append({'day': i, 'no_show_amount': no_show_daily})

            sum_no_show += no_show_daily
            multiple_df = pd.concat([multiple_df, single_df]) if i > 1 else single_df
            multiple_queue_df = pd.concat([multiple_queue_df, single_queue_df]) if i > 1 else single_queue_df
        if verbose and verbose_proportions:
            print()
        if verbose_proportions:
            print(f"wszyscy pacjeci: {sum_patients_served + sum_no_show}")
            print(f"obsluzeni pacjeci: {sum_patients_served}")
            print(f"noshow pacjeci: {sum_no_show}")
            print(f"proporcja: {sum_no_show/(sum_patients_served + sum_no_show)}")
        
        no_show_df = pd.DataFrame(no_show_per_day)
        no_show_df = no_show_df.set_index(["day"])
            
        return multiple_df, multiple_queue_df, no_show_df

In [206]:
clinic1 = Clinic(number_of_rooms=3, planned_service_time=15, sim_time=8*60, seed=42)

In [207]:
df, queue_df, nshow = clinic1.run_multiple_times(n=1000) 

df.to_csv("../wyniki/wyniki_z_um.csv")
queue_df.to_csv("../wyniki/kolejki_z_um.csv")

In [208]:
display(nshow)

      no_show_amount
day
1                 19
2                 18
3                 17
4                 16
5                 15
...              ...
996               12
997               11
998               10
999               19
1000              26

[1000 rows x 1 columns]

In [209]:
display(queue_df)

                 total_queue_length
day  time
1    0.000000                     0
     15.000000                    2
     15.993428                    1
     16.295377                    0
     30.000000                    2
...                             ...
1000 438.209552                   1
     443.703498                   0
     450.000000                   1
     452.111472                   0
     465.000000                   0

[71932 rows x 1 columns]

In [213]:
patients_lost_per_day = queue_df.groupby('day').tail(1)[['total_queue_length']]
patients_lost_per_day = patients_lost_per_day.reset_index(drop=True)
no_show_df_reset = nshow.reset_index(drop=True)
patients_lost_per_day['total_lost'] = patients_lost_per_day['total_queue_length'] + no_show_df_reset['no_show_amount']
print_statistics(patients_lost_per_day['total_queue_length'], "ostatnia długość kolejki na koniec dnia")
print_statistics(no_show_df_reset['no_show_amount'], "liczba pacjentów no-show")
print_statistics(patients_lost_per_day['total_lost'], "liczba straconych pacjentów na zamknięcie")

--- Statystyki ostatnia długość kolejki na koniec dnia ---
Średnia: 0.01
Mediana: 0.00
Odchylenie standardowe: 0.09
Min: 0.00
Max: 1.00

Percentyle:
25. percentyl: 0.00
95. percentyl: 0.00

--- Statystyki liczba pacjentów no-show ---
Średnia: 19.34
Mediana: 19.00
Odchylenie standardowe: 3.99
Min: 8.00
Max: 33.00

Percentyle:
25. percentyl: 17.00
95. percentyl: 26.00

--- Statystyki liczba straconych pacjentów na zamknięcie ---
Średnia: 19.35
Mediana: 19.00
Odchylenie standardowe: 3.99
Min: 8.00
Max: 33.00

Percentyle:
25. percentyl: 17.00
95. percentyl: 26.00

In [211]:
stats(df, queue_df)

Ilość obsłużonych pacjentów: 74966
Liczba dni symulacji: 1000

--- Statystyki średni czas oczekiwania na wizytę ---
Średnia: 1.63 min
Mediana: 1.48 min
Odchylenie standardowe: 0.72 min
Min: 0.40 min
Max: 6.47 min

Percentyle:
25. percentyl: 1.15 min
95. percentyl: 3.00 min

--- Statystyki średnia długość kolejki per dzień ---
Średnia: 0.27 osób
Mediana: 0.24 osób
Odchylenie standardowe: 0.12 osób
Min: 0.05 osób
Max: 1.06 osób

Percentyle:
25. percentyl: 0.18 osób
95. percentyl: 0.50 osób

--- Statystyki współczynnik wykorzystania lekarzy ---
Średnia: 78.01 %
Mediana: 78.11 %
Odchylenie standardowe: 4.21 %
Min: 63.87 %
Max: 89.06 %

Percentyle:
25. percentyl: 75.24 %
95. percentyl: 84.90 %