In [1]:
import matplotlib
matplotlib.use('TkAgg')  # or 'Qt5Agg'
import numpy as np
import simpy
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
from pomocnicze_funkcje import readable_time, randomized_service_time


#Naprawa importów pomocniczych funkcji po edycji ich kodu
import importlib
import pomocnicze_funkcje
importlib.reload(pomocnicze_funkcje)

Każdy obiekt w naszej symulacji jest klasą, która przechowuje informacje o sobie.

Dla pacjenta są to:
- `day`: identyfikator uruchomionej symulacji
- `id`: identyfikator Pacjenta
- `room`: gabinet, który obsłużył Pacjenta
- `arrival_time`: godzina, o której przyszedł
- `service_start_time`: godzina, o której wszedł do gabinetu (rozpoczęła się obsługa)
- `service_end_time`: godzina, o której wyszedł z gabinetu (zakończenie obsługi)

Każda zmienna **`time`** jest przechowywana jako liczba minut od rozpoczęcia symulacji

In [2]:
class Patient:
    def __init__(self, id):
        self.day = 1
        self.id = id
        self.room = None
        self.arrival_time = None
        self.service_start_time = None
        self.service_end_time = None

Dla gabinetu są to:
- `id`: identyfikator gabinetu
- `patients_served`: liczba obsłużonych pacjentów

In [3]:
class Room:
    def __init__(self, id):
        self.id = id
        self.patients_served = 0

## Parametry kliniki:
- `planned_service_time`: zaplanowany czas obsługi pacjenta [minuty]
- `lambda_per_hour`: ile pacjentów przychodzi co godzinę [pacjent/60] -> zamieniamy na minuty
- `number_of_ rooms`: liczba gabinetów
- `sim_time`: długość symulacji [minuty]

## Pomocnicze zmienne:
- `seed`: seed generatora liczb pseudolosowych
- `list_rooms`: lista gabinetów o długości `number_of_rooms`
- `rooms`: struktura Store z biblioteki simpy o wielkości `number_of_rooms`
- `queue_len_dict`: słownik przechowujący `{godzinę_zmiany:długość_kolejki}`
- `queue_array`: lista przechowywująca czekających pacjentów
- `processed_patients`: lista obsłużonych już pacjentów

In [4]:
class Clinic:
    def __init__(self, planned_service_time, lambda_per_hour=10/60, seed=None, number_of_rooms=3, sim_time=480):
        # Inicjalizacja zmiennych symulacji
        self.curr_patient_id = 1
        self.env = simpy.Environment()

        # Inicjalizacja parametrów kliniki
        self.planned_service_time = planned_service_time  # w minutach
        self.lambda_per_hour = lambda_per_hour # średnia liczba przyjęć na godzinę [pacjent/60min]
        self.list_rooms = [Room(id=i + 1) for i in range(number_of_rooms)] 
        self.rooms = simpy.Store(self.env, capacity=number_of_rooms)
        self.sim_time = sim_time  # w minutach

        # Seed jest tutaj ustawiany, aby każdy kolejny dzień używał kolejnego stanu generatora.
        self.seed = seed
        if self.seed:
            np.random.seed(self.seed)

        # Logika statystyk kolejki
        self.queue_len_dict = {}
        self.queue_array = []
        self.last_queue_length = 0

        # Inicjalizacja pokoi w klinice
        for room in self.list_rooms:
            self.rooms.put(room)

        self.processed_patients = []

In [5]:
def update_queue_len_dict(self, curr_time):
    current_length = len(self.queue_array)

    # Aktualizuj tylko jeśli długość kolejki się zmieniła
    if current_length != self.last_queue_length:
        self.queue_len_dict[curr_time] = current_length
        self.last_queue_length = current_length

Clinic.update_queue_len_dict = update_queue_len_dict

In [6]:
def time_between_new_patients(self):
    return np.random.exponential(1/self.lambda_per_hour) # w minutach

Clinic.time_between_new_patients = time_between_new_patients

In [7]:
def generate_patients(self, verbose=False):
    while True:
        # Pacjenci nie przychodzą {service_time} przed zamknięciem
        if self.env.now >= self.sim_time-self.planned_service_time: 
            break
        patient = Patient(id=self.curr_patient_id)
        patient.arrival_time = self.env.now
        if verbose:
            print(f"Czas {readable_time(self.env.now)}: Pacjent {patient.id} przybył do kliniki")
        self.env.process(self.serve_patient(patient, verbose=verbose))
        self.curr_patient_id += 1
        yield self.env.timeout(self.time_between_new_patients())

Clinic.generate_patients = generate_patients

In [8]:
def serve_patient(self, patient, verbose=False): 

    # Pacjent wchodzi do kolejki 
    self.queue_array.append(patient.id)
    self.update_queue_len_dict(curr_time=self.env.now)

    # Funkcja w pomocnicze_funkcje.py
    real_service_time = randomized_service_time(mean=self.planned_service_time, std=2, minimal_time=5)

    # Nie zdążyło obsłużyć pacjenta przed zamknięciem
    if self.env.now >= self.sim_time-self.planned_service_time: 
        if verbose:
            print(f"Czas {readable_time(self.env.now)}: Pacjent {patient.id} - nie zdążył zostać obsłużony przed zamknięciem kliniki")
        self.queue_array.remove(patient.id)
        self.update_queue_len_dict(curr_time=self.env.now)
        return
    
    # POBRANIE GABINETU - czytaj Pacjent wchodzi do kolejki do gabinetu
    room = yield self.rooms.get()  

    # Dalsza część wykonuje się po wyjściu z kolejki, czyli po rozpoczęciu obsługi

    # Klient opuszcza kolejkę
    self.queue_array.remove(patient.id)
    self.update_queue_len_dict(curr_time=self.env.now)

    # Zaczyna się obsługa pacjenta
    patient.service_start_time = self.env.now
    if verbose:
        print(f"Czas {readable_time(self.env.now)}: Pacjent {patient.id} wchodzi do gabinetu {room.id} ")

    # Mija czas obsługi
    yield self.env.timeout(real_service_time) 

    # Zapisujemy kiedy wychodzi z gabinetu
    patient.service_end_time = self.env.now
    room.patients_served += 1
    if verbose:
        print(f"Czas {readable_time(self.env.now)}: Pacjent {patient.id} wychodzi z gabinetu {room.id}, czekal od {readable_time(patient.arrival_time)} do {readable_time(patient.service_start_time)}")
    # Przypisanie jaki gabinet obsługiwał pacjenta
    patient.room = room.id
    self.processed_patients.append(patient)

    # ZWROT GABINETU - czytaj Pacjent opuszcza gabinet
    yield self.rooms.put(room)

Clinic.serve_patient = serve_patient

In [ ]:
def run(self, day=1, verbose=False):
    if verbose:
        print(self.env.now) 

    # Rozpoczęcie generowania pacjentów
    self.env.process(self.generate_patients(verbose=verbose)) 

    #UWAGA: env.run to nie to samo co ta funkcja (run)! env.run uruchamia symulację, run() to metoda klasy Clinic.
    self.env.run(until=self.sim_time)   
    
    # Wyciągnięcie danych o obsłużonych pacjentach do DataFrame
    df = pd.DataFrame([
    {
        "day": day,
        "id": p.id,
        "room": p.room,
        "arrival_time": p.arrival_time,
        "service_start_time": p.service_start_time,
        "service_end_time": p.service_end_time,
        "real_service_time": p.service_end_time - p.service_start_time,
        "waiting_time": p.service_start_time - p.arrival_time
    }
    for p in self.processed_patients
    ])

    # Wyciągnięcie danych o długości kolejki do DataFrame
    df_kolejka = pd.DataFrame([
    {
        "day": day,
        "time": time,
        "queue_length": length
    }
    for time, length in self.queue_len_dict.items()
    ])

    return df.set_index(["day", "id"]), df_kolejka
Clinic.run = run

In [10]:
def reset(self): # Resetuje stan kliniki do początkowego między dniami symulacji
    self.env = simpy.Environment()
    self.curr_patient_id = 1
    self.list_rooms = [Room(id=i + 1) for i in range(len(self.list_rooms))]
    self.rooms = simpy.Store(self.env, capacity=len(self.list_rooms))
    for room in self.list_rooms:
        self.rooms.put(room)
    self.processed_patients = []

    # Reset statystyk kolejki: WAŻNE! (inaczej DF kolejki ma 64 MILIONY rekordów i waży 2 GB)
    self.queue_len_dict = {}
    self.queue_array = []
    self.last_queue_length = 0

Clinic.reset = reset

In [11]:
def run_multiple_times(self, n, verbose=False):
    list_dfs = []
    list_dfs_queue = []
    for i in range(1, n+1):
        if verbose:
            print(f"-----------{i}-----------")
        self.reset()
        single_df = self.run(i, verbose=verbose)
        list_dfs.append(single_df[0])
        list_dfs_queue.append(single_df[1])

    # Szybsze scalanie wyników (lepiej zmienić listę na DF niż ciągle doklejać)
    multiple_df = pd.concat(list_dfs)
    multiple_df_queue = pd.concat(list_dfs_queue)
    return multiple_df, multiple_df_queue   

Clinic.run_multiple_times = run_multiple_times

In [12]:
clinic = Clinic(number_of_rooms=3, planned_service_time=15, sim_time=480, lambda_per_hour=10/60)

In [13]:
# single_df = clinic.run(day=1)
df, df_kolejka = clinic.run_multiple_times(n=1000, verbose=False)

In [14]:
# df.to_csv("../wyniki/wyniki_bez_um.csv")
# df_kolejka.to_csv("../wyniki/wyniki_kolejka_bez_um.csv")

In [16]:
df.head()

        room  arrival_time  service_start_time  service_end_time  waiting_time
day id
1   1      1      0.000000            0.000000         17.879362      0.000000
    3      3      7.169396            7.169396         18.900626      0.000000
    2      2      4.350235            4.350235         21.080126      0.000000
    4      1     11.673130           17.879362         32.127447      6.206233
    5      3     27.649849           27.649849         42.929461      0.000000

In [19]:
df_kolejka.describe()

                 day           time   queue_length
count  128434.000000  128434.000000  128434.000000
mean      499.304514     239.256920       2.066057
std       288.606027     134.946322       2.365239
min         1.000000       0.000000       0.000000
25%       249.000000     123.594096       0.000000
50%       499.000000     241.093748       1.000000
75%       750.000000     356.311473       3.000000
max      1000.000000     479.998145      18.000000