In [949]:
import matplotlib
matplotlib.use('TkAgg')  # or 'Qt5Agg'
import numpy as np
import simpy
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
from pomocnicze_funkcje import readable_time, randomized_service_time, stats, print_statistics


#Naprawa importów pomocniczych funkcji po edycji ich kodu
import importlib
import pomocnicze_funkcje
importlib.reload(pomocnicze_funkcje)

Każdy obiekt w naszej symulacji jest klasą, która przechowuje informacje o sobie.

Dla pacjenta są to:
- `day`: identyfikator uruchomionej symulacji
- `id`: identyfikator Pacjenta
- `room`: gabinet, który obsłużył Pacjenta
- `arrival_time`: godzina, o której przyszedł
- `service_start_time`: godzina, o której wszedł do gabinetu (rozpoczęła się obsługa)
- `service_end_time`: godzina, o której wyszedł z gabinetu (zakończenie obsługi)

Każda zmienna **`time`** jest przechowywana jako liczba minut od rozpoczęcia symulacji

In [950]:
class Patient:
    def __init__(self, id):
        self.day = 1
        self.id = id
        self.room = None
        self.arrival_time = None
        self.service_start_time = None
        self.service_end_time = None

Dla gabinetu są to:
- `id`: identyfikator gabinetu
- `patients_served`: liczba obsłużonych pacjentów

In [951]:
class Room:
    def __init__(self, id):
        self.id = id
        self.patients_served = 0

## Parametry kliniki:
- `planned_service_time`: zaplanowany czas obsługi pacjenta [minuty]
- `lambda_per_hour`: ile pacjentów przychodzi co godzinę [pacjent/60] -> zamieniamy na minuty
- `number_of_ rooms`: liczba gabinetów
- `sim_time`: długość symulacji [minuty]

## Pomocnicze zmienne:
- `seed`: seed generatora liczb pseudolosowych
- `list_rooms`: lista gabinetów o długości `number_of_rooms`
- `rooms`: struktura Store z biblioteki simpy o wielkości `number_of_rooms`
- `queue_len_dict`: słownik przechowujący `{godzinę_zmiany:długość_kolejki}`
- `queue_array`: lista przechowywująca czekających pacjentów
- `last_queue_length`: ostatnia długość kolejki - do aktualizacji słownika tylko gdy zmienia się długość kolejki
- `processed_patients`: lista obsłużonych już pacjentów


Zmienna `randomized` jest tylko na poczet przypadku deterministycznego niżej i zmienia prawdziwy czas obsługi (Zamiast rozkładu normalnego używamy `planned_service_time`)

In [952]:
class Clinic:
    def __init__(self, planned_service_time, lambda_per_hour=10/60, seed=None, number_of_rooms=3, sim_time=480, randomized=True):
        # Inicjalizacja zmiennych symulacji
        self.curr_patient_id = 1
        self.env = simpy.Environment()
        self.randomized = randomized

        # Inicjalizacja parametrów kliniki
        self.planned_service_time = planned_service_time  # w minutach
        self.lambda_per_hour = lambda_per_hour # średnia liczba przyjęć na godzinę [pacjent/60min]
        self.list_rooms = [Room(id=i + 1) for i in range(number_of_rooms)] 
        self.rooms = simpy.Store(self.env, capacity=number_of_rooms)
        self.sim_time = sim_time  # w minutach

        # Seed jest tutaj ustawiany, aby każdy kolejny dzień używał kolejnego stanu generatora.
        self.seed = seed
        if self.seed:
            np.random.seed(self.seed)

        # Logika statystyk kolejki
        self.queue_len_dict = {}
        self.queue_array = []
        self.last_queue_length = 0

        # Inicjalizacja pokoi w klinice
        for room in self.list_rooms:
            self.rooms.put(room)

        self.processed_patients = []

### Metoda `update_queue_len_dict()`
Funkcja aktualizuje słownik kolejki TYLKO jeśli długość kolejki się zmieniła

In [953]:
def update_queue_len_dict(self, curr_time):
    current_length = len(self.queue_array)

    # Aktualizuj tylko jeśli długość kolejki się zmieniła
    if current_length != self.last_queue_length:
        self.queue_len_dict[curr_time] = current_length
        self.last_queue_length = current_length

Clinic.update_queue_len_dict = update_queue_len_dict

### Metoda `time_between_new_patients()`:
Ważna metoda zwracająca przerwę w minutach, do pojawienia się następnego pacjenta, podawana jest jako parametr metody `env.timeout()` po wygenerowaniu pacjenta.

Wykorzystuje rozkład wykładniczy o intensywności $\frac{1}{\lambda}$

In [954]:
def time_between_new_patients(self):
    return np.random.exponential(1/self.lambda_per_hour) # w minutach

Clinic.time_between_new_patients = time_between_new_patients

### Metoda `generate_patients()`:

Metoda wygeneruje pacjenta o jakimś `id` i rozpocznie dla niego proces `serve_patient()`, aż do momentu `{service_time}` przed zamknięciem. Dzięki niej upłynie czas do przyjścia nastepnego pacjenta

In [955]:
def generate_patients(self, verbose=False):
    while True:
        # Pacjenci nie przychodzą {service_time} przed zamknięciem
        if self.env.now >= self.sim_time-self.planned_service_time: 
            break
        patient = Patient(id=self.curr_patient_id)
        patient.arrival_time = self.env.now
        if verbose:
            print(f"Czas {readable_time(self.env.now)}: Pacjent {patient.id} przybył do kliniki")
        self.env.process(self.serve_patient(patient, verbose=verbose))
        self.curr_patient_id += 1
        yield self.env.timeout(self.time_between_new_patients())

Clinic.generate_patients = generate_patients

### Metoda `serve_patient(patient)`

Odpalana dla jakiegoś pacjenta:
- Dodaje go do kolejki
- Sprawdza czy jeszcze można obsłużyć pacjenta - jeśli mija godzina `{service_time}` od końca pracy `(sim_time)` wtedy pacjenci są usuwani z kolejki.
- Sprawdza czy jakiś pokój jest wolny i dodaje go do kolejki (Prawdziwa kolejka jest wbudowana w `SimPy` i uruchamiana jest przez `rooms.get()`)
- Obsługuje pacjentów i puszcza czas dalej.
- Zapisuje kiedy i jaki pacjent wyszedł z gabinetu
- Zwraca gabinet do puli

In [956]:
def serve_patient(self, patient, verbose=False): 

    # Pacjent wchodzi do kolejki 
    self.queue_array.append(patient.id)
    self.update_queue_len_dict(curr_time=self.env.now)

    # Funkcja w pomocnicze_funkcje.py
    if self.randomized:
        real_service_time = randomized_service_time(mean=self.planned_service_time, std=2, minimal_time=5)
    else:
        real_service_time = self.planned_service_time

    # Nie zdążyło obsłużyć pacjenta przed zamknięciem
    if self.env.now >= self.sim_time-self.planned_service_time: 
        if verbose:
            print(f"Czas {readable_time(self.env.now)}: Pacjent {patient.id} - nie zdążył zostać obsłużony przed zamknięciem kliniki")
        self.queue_array.remove(patient.id)
        self.update_queue_len_dict(curr_time=self.env.now)
        return
    
    # POBRANIE GABINETU - czytaj Pacjent wchodzi do kolejki do gabinetu
    room = yield self.rooms.get()  

    # Dalsza część wykonuje się po wyjściu z kolejki, czyli po rozpoczęciu obsługi

    # Klient opuszcza kolejkę
    self.queue_array.remove(patient.id)
    self.update_queue_len_dict(curr_time=self.env.now)

    # Zaczyna się obsługa pacjenta
    patient.service_start_time = self.env.now
    if verbose:
        print(f"Czas {readable_time(self.env.now)}: Pacjent {patient.id} wchodzi do gabinetu {room.id} ")

    # Mija czas obsługi
    yield self.env.timeout(real_service_time) 

    # Zapisujemy kiedy wychodzi z gabinetu
    patient.service_end_time = self.env.now
    room.patients_served += 1
    if verbose:
        print(f"Czas {readable_time(self.env.now)}: Pacjent {patient.id} wychodzi z gabinetu {room.id}, czekal od {readable_time(patient.arrival_time)} do {readable_time(patient.service_start_time)}")
    # Przypisanie jaki gabinet obsługiwał pacjenta
    patient.room = room.id
    self.processed_patients.append(patient)

    # ZWROT GABINETU - czytaj Pacjent opuszcza gabinet
    yield self.rooms.put(room)

Clinic.serve_patient = serve_patient

### Metoda `run()` 
Uruchamia symulacje, rozpoczyna proces generowania pacjentów i wyciąga dane z odpowiednich list do DataFrame-ów.

In [957]:
def run(self, day=1, verbose=False):
    if verbose:
        print(self.env.now) 

    # Rozpoczęcie generowania pacjentów
    self.env.process(self.generate_patients(verbose=verbose)) 

    #UWAGA: env.run to nie to samo co ta funkcja (run)! env.run uruchamia symulację, run() to metoda klasy Clinic.
    self.env.run(until=self.sim_time)   
    
    # Wyciągnięcie danych o obsłużonych pacjentach do DataFrame
    df = pd.DataFrame([
    {
        "day": day,
        "id": p.id,
        "room": p.room,
        "arrival_time": p.arrival_time,
        "service_start_time": p.service_start_time,
        "service_end_time": p.service_end_time,
        "service_time": p.service_end_time - p.service_start_time,
        "waiting_time": p.service_start_time - p.arrival_time
    }
    for p in self.processed_patients
    ])

    # Wyciągnięcie danych o długości kolejki do DataFrame
    df_kolejka = pd.DataFrame([
    {
        "day": day,
        "time": time,
        "queue_length": length
    }
    for time, length in self.queue_len_dict.items()
    ])

    return df.set_index(["day", "id"]), df_kolejka.set_index(["day", "time"])
Clinic.run = run

### Metoda `reset()`
Resetuje informacje między symulacjami (dniami).

In [958]:
def reset(self): # Resetuje stan kliniki do początkowego między dniami symulacji
    self.env = simpy.Environment()
    self.curr_patient_id = 1
    self.list_rooms = [Room(id=i + 1) for i in range(len(self.list_rooms))]
    self.rooms = simpy.Store(self.env, capacity=len(self.list_rooms))
    for room in self.list_rooms:
        self.rooms.put(room)
    self.processed_patients = []

    # Reset statystyk kolejki: WAŻNE! (inaczej DF kolejki ma 64 MILIONY rekordów i waży 2 GB)
    self.queue_len_dict = {}
    self.queue_array = []
    self.last_queue_length = 0

Clinic.reset = reset

### Metoda `run_multiple_times`

Tworzy nowe środowisko dla każdego uruchomienia i łączy wyniki do DataFrame'a `multiple_df`

*Stworzenie nowego środowiska nie zmienia seeda ani stanu generatora liczb - każdy następny dzień używa następnego stanu generatora.*

In [959]:
def run_multiple_times(self, n, verbose=False):
    list_dfs = []
    list_dfs_queue = []
    for i in range(1, n+1):
        if verbose:
            print(f"-----------{i}-----------")
        self.reset()
        single_df = self.run(i, verbose=verbose)
        list_dfs.append(single_df[0])
        list_dfs_queue.append(single_df[1])

    # Szybsze scalanie wyników (lepiej zmienić listę na DF niż ciągle doklejać)
    multiple_df = pd.concat(list_dfs)
    multiple_df_queue = pd.concat(list_dfs_queue)
    return multiple_df, multiple_df_queue   

Clinic.run_multiple_times = run_multiple_times

In [960]:
clinic = Clinic(number_of_rooms=3, planned_service_time=15, sim_time=480, lambda_per_hour=10/60, seed=42, randomized=True)

In [961]:
# single_df = clinic.run(day=1)
df, df_kolejka = clinic.run_multiple_times(n=1000, verbose=False)

In [962]:
# df.to_csv("../wyniki/wyniki_bez_um.csv")
# df_kolejka.to_csv("../wyniki/wyniki_kolejka_bez_um.csv")

In [963]:
df.head()

        room  arrival_time  service_start_time  service_end_time  \
day id
1   1      1      0.000000            0.000000         12.776240
    2      2      2.815609            2.815609         18.453413
    3      3      3.833186            3.833186         19.391269
    4      1      4.192219           12.776240         29.797270
    5      2     11.579719           18.453413         32.291657

        service_time  waiting_time
day id
1   1      12.776240      0.000000
    2      15.637804      0.000000
    3      15.558083      0.000000
    4      17.021031      8.584021
    5      13.838244      6.873694

In [964]:
df_kolejka.describe()

        queue_length
count  128429.000000
mean        2.181493
std         2.546039
min         0.000000
25%         0.000000
50%         1.000000
75%         3.000000
max        24.000000

In [965]:
stats(df, df_kolejka, service_minutes=15, total_time_hours=8)

Ilość obsłużonych pacjentów: 76641
Liczba dni symulacji: 1000

--- Statystyki średni czas oczekiwania na wizytę ---
Średnia: 8.19 min
Mediana: 6.31 min
Odchylenie standardowe: 6.58 min
Min: 0.59 min
Max: 47.49 min

Percentyle:
25. percentyl: 3.99 min
95. percentyl: 22.40 min

--- Statystyki średnia długość kolejki per dzień ---
Średnia: 1.47 osób
Mediana: 1.05 osób
Odchylenie standardowe: 1.35 osób
Min: 0.06 osób
Max: 10.60 osób

Percentyle:
25. percentyl: 0.64 osób
95. percentyl: 4.25 osób

--- Statystyki współczynnik wykorzystania lekarzy ---
Średnia: 79.78 %
Mediana: 79.91 %
Odchylenie standardowe: 8.20 %
Min: 56.64 %
Max: 98.49 %

Percentyle:
25. percentyl: 74.14 %
95. percentyl: 93.10 %

In [966]:
# histogram obsłużonych pacjentów (kubełki ile pacjentów na dzień)
num_patients_per_day = df.groupby('day').size()

In [967]:
plt.figure(figsize=(10, 6))
sns.histplot(num_patients_per_day, bins=15, kde=True)
plt.title('Histogram liczby obsłużonych pacjentów na dzień')
plt.xlabel('Liczba pacjentów na dzień')
plt.ylabel('Liczba dni')
plt.show()

print_statistics(num_patients_per_day, "liczba obsłużonych pacjentów na dzień")

--- Statystyki liczba obsłużonych pacjentów na dzień ---
Średnia: 76.64
Mediana: 77.00
Odchylenie standardowe: 7.86
Min: 53.00
Max: 96.00

Percentyle:
25. percentyl: 71.00
95. percentyl: 89.00

In [969]:
# Histogram ile straciliśmy pacjentów każdego dnia na zamknięcie (ostatni moment z dnia przed zamknięciem) 
# day jest multiindexem
# df_kolejka mówi o stracie klientów gdy klinika się zamyka

patients_lost_per_day = df_kolejka.groupby('day').tail(1)['queue_length']

plt.figure(figsize=(10, 6))
sns.histplot(patients_lost_per_day, bins=15, kde=True, color='coral')
plt.title('Histogram liczby straconych pacjentów na zamknięcie')
plt.xlabel('Liczba pacjentów w kolejce na zamknięcie')
plt.ylabel('Liczba dni')
plt.show()

# Statystyki
print_statistics(patients_lost_per_day, "liczba straconych pacjentów na zamknięcie")

--- Statystyki liczba straconych pacjentów na zamknięcie ---
Średnia: 0.63
Mediana: 0.00
Odchylenie standardowe: 1.68
Min: 0.00
Max: 14.00

Percentyle:
25. percentyl: 0.00
95. percentyl: 4.00

## Prosty przykład (deterministyczny)

Opis zasad:
- Dla ułatwienia obliczeń pacjenci przychodzą w deterministycznych, równych odstępach czasu
- Przychodzi 6 pacjentów na godzinę (czyli przychodzą w odstępach 10 minut)
- czas trwania symulacji = 2 godziny
- czas jednej wizyty = 15 minut
- są dwa gabinety

| Czas | Zdarzenia|                              |start|koniec|                                       |
|:------:|:-----------:|------------------------------|:-----:|:------:|-----------------------------------------|
| 8:00 | Pacjent 1 wchodzi do Gabinetu 1|        |8:00|8:15|                                          |
| 8:10 | Pacjent 2 wchodzi do Gabinetu 2|        |8:10|8:25|                                          |
| 8:15 | Pacjent 1 `zwalnia` Gabinet 1 |               |-|-|                                            |
| 8:20 | Pacjent 3 wchodzi do Gabinetu 1 |        |8:20|8:35|                                         |
| 8:25 | Pacjent 2 `zwalnia` Gabinet 2  |              |-|-|                                            |
| 8:30 | Pacjent 4 wchodzi do Gabinetu 2 |        |8:30|8:45|                                         |
| 8:35 | Pacjent 3 `zwalnia` Gabinet 1   |             |-|-|                                            |
| 8:40 | Pacjent 5 wchodzi do Gabinetu 1 |       |8:40|8:55|                                          |
| 8:45 | Pacjent 4 `zwalnia` Gabinet 2   |             |-|-|                                            |
| 8:50 | Pacjent 6 wchodzi do Gabinetu 2 |      |8:50|9:05|                                           |
| 8:55 | Pacjent 5 `zwalnia` Gabinet 1   |             |-|-|                                            |
| 9:00 | Pacjent 7 wchodzi do Gabinetu 1 |       |9:00|9:15|                                          |
| 9:05 | Pacjent 6 `zwalnia` Gabinet 2   |             |-|-|                                            |
| 9:10 | Pacjent 8 wchodzi do Gabinetu 2 |       |9:10|9:25|                                          |
| 9:15 | Pacjent 7 `zwalnia` Gabinet 1  |              |-|-|                                            |
| 9:20 | Pacjent 9 wchodzi do Gabinetu 1  |      |9:20|9:35|                                          |
| 9:25 | Pacjent 8 `zwalnia` Gabinet 2   |             |-|-|                                            |
| 9:30 | Pacjent 10 wchodzi do Gabinetu 2 |       |9:30|9:45|                                         |
| 9:35 | Pacjent 9 `zwalnia` Gabinet 1    |            |-|-|                                            |
| 9:40 | Pacjent 11 wchodzi do Gabinetu 1  |       |9:40|9:55|                                        |
| 9:45 | Pacjent 10 `zwalnia` Gabinet 2    |           |-|-|                                            |
| 9:45 | Koniec przyjmowania pacjentów.   |          |-|-|                                            |
| 9:55 | Pacjent 11 `zwalnia` Gabinet 1   |            |-|-|                                            |
| 10:00 | Koniec symulacji          |                |-|-|                                            |

Podczas tej symulacji

Przyjmujemy deterministyczny przypadek przez ustawienie czasu między pacjentami jako 10 minut.
Jako, że nie ma tutaj losowości wystarczy pojedyńczy przypadek.

In [970]:
def time_between_new_patients(self):
    return 10
Clinic.time_between_new_patients = time_between_new_patients

In [971]:
clinic_deterministic = Clinic(number_of_rooms=2, planned_service_time=15, sim_time=120, lambda_per_hour=6/60, randomized=False)

In [972]:
# single_df = clinic_deterministic.run(day=1)
df = clinic_deterministic.run(day=1, verbose=True)

0
Czas 8:00: Pacjent 1 przybył do kliniki
Czas 8:00: Pacjent 1 wchodzi do gabinetu 1
Czas 8:10: Pacjent 2 przybył do kliniki
Czas 8:10: Pacjent 2 wchodzi do gabinetu 2
Czas 8:15: Pacjent 1 wychodzi z gabinetu 1, czekal od 8:00 do 8:00
Czas 8:20: Pacjent 3 przybył do kliniki
Czas 8:20: Pacjent 3 wchodzi do gabinetu 1
Czas 8:25: Pacjent 2 wychodzi z gabinetu 2, czekal od 8:10 do 8:10
Czas 8:30: Pacjent 4 przybył do kliniki
Czas 8:30: Pacjent 4 wchodzi do gabinetu 2
Czas 8:35: Pacjent 3 wychodzi z gabinetu 1, czekal od 8:20 do 8:20
Czas 8:40: Pacjent 5 przybył do kliniki
Czas 8:40: Pacjent 5 wchodzi do gabinetu 1
Czas 8:45: Pacjent 4 wychodzi z gabinetu 2, czekal od 8:30 do 8:30
Czas 8:50: Pacjent 6 przybył do kliniki
Czas 8:50: Pacjent 6 wchodzi do gabinetu 2
Czas 8:55: Pacjent 5 wychodzi z gabinetu 1, czekal od 8:40 do 8:40
Czas 9:00: Pacjent 7 przybył do kliniki
Czas 9:00: Pacjent 7 wchodzi do gabinetu 1
Czas 9:05: Pacjent 6 wychodzi z gabinetu 2, czekal od 8:50 do 8:50
Czas 9:10: Pacjent 8 przybył do kliniki
Czas 9:10: Pacjent 8 wchodzi do gabinetu 2
Czas 9:15: Pacjent 7 wychodzi z gabinetu 1, czekal od 9:00 do 9:00
Czas 9:20: Pacjent 9 przybył do kliniki
Czas 9:20: Pacjent 9 wchodzi do gabinetu 1
Czas 9:25: Pacjent 8 wychodzi z gabinetu 2, czekal od 9:10 do 9:10
Czas 9:30: Pacjent 10 przybył do kliniki
Czas 9:30: Pacjent 10 wchodzi do gabinetu 2
Czas 9:35: Pacjent 9 wychodzi z gabinetu 1, czekal od 9:20 do 9:20
Czas 9:40: Pacjent 11 przybył do kliniki
Czas 9:40: Pacjent 11 wchodzi do gabinetu 1
Czas 9:45: Pacjent 10 wychodzi z gabinetu 2, czekal od 9:30 do 9:30
Czas 9:55: Pacjent 11 wychodzi z gabinetu 1, czekal od 9:40 do 9:40

### Teoria (deterministyczna) zgadza się z symulacją